### ISSUE TITLE
无法使用，老是报错！

### ISSUE THREAD

**Issue by ListenV** [jsmith/vuepress-theme-terminal#1]
如题
![错误](https://sky03-blog-images.oss-cn-beijing.aliyuncs.com/blog-img/QQ截图20191211001258.png)

**Comment by jsmith** [comment]
抱歉，当前已被破坏。在README.md文件中，我声明由于Webpack出现问题。不幸的是，我还没有时间修复此错误。自从您打开此问题以来，我将在本周末尝试修复该错误 :)

**Comment by ListenV** [comment]
那么，期待您的修复。

> Looking forward to your repair.

**Comment by jsmith** [comment]
好的，现在尝试 :)

**Comment by ListenV** [comment]
OK，thank you very much.------------------ 原始邮件 ------------------
发件人: "Jacob Smith"<notifications@github.com>
发送时间: 2019年12月18日(星期三) 凌晨5:48
收件人: "jsmith/vuepress-theme-terminal"<vuepress-theme-terminal@noreply.github.com>;
抄送: "skyls03"<skyls03@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jsmith/vuepress-theme-terminal] 无法使用，老是报错！ (#1)



好的，现在尝试 :)
 
&mdash;
